### ISSUE TITLE
 Your text description is not the same as your under picture

### ISSUE THREAD

**Issue by imgiang** [pancake-llc/play-asset-delivery-addressable#1]
Your Readme.txt file has some mistakes. your direction is wrong and misses some steps.  Your text description is not the same as your under picture. please check again and fix it. Thank u for your package.
![err](https://github.com/pancake-llc/play-asset-delivery-addressable/assets/79862204/8e9f496f-7f10-4867-b67b-6e47813ea45a)

**Comment by aprius** [comment]
Thanks you i will check and fix this

**Comment by aprius** [comment]
Fixed in #2
